### ISSUE TITLE
FR: download & open a file with default application

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/CompuMaster.Dms#2]
## ToDos for implementation

* [x] Add symbol button in dialog to download 1 or more selected files and open it/them
* [x] Implement button in dialog to download 1 or more selected files and open it/them
* [x] Display button only if flagged to display
